name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual runs from the Actions UI
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Vite requires Node >= 20.19.0 (or 22.12+). Use a compatible 20.x version.
          node-version: '20.19.0'
          cache: 'npm'

      - name: Show Node and npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        # Use --legacy-peer-deps to avoid ERESOLVE peer dependency failures in the Actions environment
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist