name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
          
      - run: npm install
      - run: chmod +x node_modules/.bin/*
      - name: Install rollup native binding fallback (Linux x64)
        run: |
          # Try to install the native rollup optional binding for the runner's platform
          npm install @rollup/rollup-linux-x64-gnu --no-save || true
          # Also try the musl variant just in case (will be ignored if not applicable)
          npm install @rollup/rollup-linux-x64-musl --no-save || true
      - name: Reinstall esbuild binary for current platform
        run: |
          if [ -f node_modules/esbuild/install.js ]; then
            node node_modules/esbuild/install.js || true
          fi
      - run: npm run build
      
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: deliaxe-paint.anarka.de
