name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
          
      - name: Install dependencies (force platform-specific optional deps)
        run: |
          echo "Removing committed package-lock.json and node_modules so npm can install platform-native optional deps for the runner"
          rm -f package-lock.json || true
          rm -rf node_modules || true
          npm install
      - name: Diagnostics - runner platform and node
        run: |
          node -e "console.log(JSON.stringify({platform: process.platform, arch: process.arch, node: process.version, execPath: process.execPath}))"
      - name: Diagnostics - list @swc files
        run: |
          ls -la node_modules/@swc || true
          ls -la node_modules/@swc/core || true
          head -n 80 node_modules/@swc/core/binding.js || true
      - name: Diagnostics - try require @swc/core (non-fatal)
        run: |
          node -e "try{ require('@swc/core'); console.log('require:@swc/core: OK') } catch(e) { console.error('require:@swc/core: FAILED', e && e.message); console.error(e && e.stack); }"
      - run: chmod +x node_modules/.bin/*
      - name: Install rollup native binding fallback (Linux x64)
        run: |
          # Try to install the native rollup optional binding for the runner's platform
          npm install @rollup/rollup-linux-x64-gnu --no-save || true
          # Also try the musl variant just in case (will be ignored if not applicable)
          npm install @rollup/rollup-linux-x64-musl --no-save || true
      - name: Diagnostics - verify rollup native package
        run: |
          echo "npm ls for @rollup packages"
          npm ls @rollup/rollup-linux-x64-gnu --json || true
          npm ls @rollup/rollup-linux-x64-musl --json || true
          echo "listing node_modules/@rollup"
          ls -la node_modules/@rollup || true
          echo "listing node_modules/@rollup/rollup-linux-x64-gnu"
          ls -la node_modules/@rollup/rollup-linux-x64-gnu || true
          echo "trying to require the rollup native package (non-fatal)"
          node -e "try{ console.log(require.resolve('@rollup/rollup-linux-x64-gnu')) } catch(e){ console.error('require rollup-native failed', e && e.message) }" || true
      - name: Reinstall esbuild binary for current platform
        run: |
          if [ -f node_modules/esbuild/install.js ]; then
            node node_modules/esbuild/install.js || true
          fi
      - name: Rebuild @swc/core native binding for current platform
        run: |
          if [ -d node_modules/@swc/core ]; then
            # Try to update the bundled binary for the current platform
            npm rebuild @swc/core --update-binary || true
            # Fallback to running the install script if rebuild didn't provide binary
            node node_modules/@swc/core/install.js || true
          fi
      - name: Install @swc/core platform-specific packages (linux x64)
        run: |
          # Try explicit platform packages for @swc/core (use the gnu/musl suffixes published by @swc)
          npm install @swc/core-linux-x64-gnu --no-save || true
          npm install @swc/core-linux-x64-musl --no-save || true
      - name: Diagnostics - list @swc files after install attempts
        run: |
          ls -la node_modules/@swc || true
          ls -la node_modules/@swc/core || true
          node -e "try{ require('@swc/core'); console.log('post-install: require:@swc/core: OK') } catch(e) { console.error('post-install: require:@swc/core: FAILED', e && e.message); console.error(e && e.stack); }"
      - name: Force @swc/core postinstall and rebuild (try to fetch correct binary)
        run: |
          echo "Running postinstall/install/rebuild for @swc/core"
          if [ -f node_modules/@swc/core/postinstall.js ]; then
            node node_modules/@swc/core/postinstall.js || true
          fi
          if [ -f node_modules/@swc/core/install.js ]; then
            node node_modules/@swc/core/install.js || true
          fi
          npm rebuild @swc/core --update-binary || true
          echo "Listing possible swc-native packages and files"
          ls -la node_modules | grep swc || true
          ls -la node_modules/@swc* || true
          ls -la node_modules/@swc/core || true
      - run: npm run build
      
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: deliaxe-paint.anarka.de
